//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace win.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/checkPwd", ReplyAction="http://tempuri.org/IUser/checkPwdResponse")]
        bool checkPwd(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/checkPwd", ReplyAction="http://tempuri.org/IUser/checkPwdResponse")]
        System.Threading.Tasks.Task<bool> checkPwdAsync(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/getUserID", ReplyAction="http://tempuri.org/IUser/getUserIDResponse")]
        int getUserID(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/getUserID", ReplyAction="http://tempuri.org/IUser/getUserIDResponse")]
        System.Threading.Tasks.Task<int> getUserIDAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/checkPerimission", ReplyAction="http://tempuri.org/IUser/checkPerimissionResponse")]
        bool checkPerimission(int userid, int projectStatuID, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/checkPerimission", ReplyAction="http://tempuri.org/IUser/checkPerimissionResponse")]
        System.Threading.Tasks.Task<bool> checkPerimissionAsync(int userid, int projectStatuID, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/hsaCheckPermission", ReplyAction="http://tempuri.org/IUser/hsaCheckPermissionResponse")]
        bool hsaCheckPermission(int userid, int projectStatuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/hsaCheckPermission", ReplyAction="http://tempuri.org/IUser/hsaCheckPermissionResponse")]
        System.Threading.Tasks.Task<bool> hsaCheckPermissionAsync(int userid, int projectStatuID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : win.UserService.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<win.UserService.IUser>, win.UserService.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkPwd(string username, string pwd) {
            return base.Channel.checkPwd(username, pwd);
        }
        
        public System.Threading.Tasks.Task<bool> checkPwdAsync(string username, string pwd) {
            return base.Channel.checkPwdAsync(username, pwd);
        }
        
        public int getUserID(string username) {
            return base.Channel.getUserID(username);
        }
        
        public System.Threading.Tasks.Task<int> getUserIDAsync(string username) {
            return base.Channel.getUserIDAsync(username);
        }
        
        public bool checkPerimission(int userid, int projectStatuID, int type) {
            return base.Channel.checkPerimission(userid, projectStatuID, type);
        }
        
        public System.Threading.Tasks.Task<bool> checkPerimissionAsync(int userid, int projectStatuID, int type) {
            return base.Channel.checkPerimissionAsync(userid, projectStatuID, type);
        }
        
        public bool hsaCheckPermission(int userid, int projectStatuID) {
            return base.Channel.hsaCheckPermission(userid, projectStatuID);
        }
        
        public System.Threading.Tasks.Task<bool> hsaCheckPermissionAsync(int userid, int projectStatuID) {
            return base.Channel.hsaCheckPermissionAsync(userid, projectStatuID);
        }
    }
}
