//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string projectID { get; set; }
        public string department { get; set; }
        public string postision { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual project project { get; set; }
    }
}
