//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public string projectID { get; set; }
        public int projectStatu { get; set; }
        public bool statu { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<System.DateTime> readtime { get; set; }
    
        public virtual project project { get; set; }
        public virtual projectStatus projectStatu1 { get; set; }
        public virtual user user { get; set; }
    }
}
