//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.checkResult = new HashSet<checkResult>();
            this.customer = new HashSet<customer>();
            this.resourcePath = new HashSet<resourcePath>();
            this.notices = new HashSet<notice>();
            this.projectStatuChangeInfoes = new HashSet<projectStatuChangeInfo>();
            this.productInfoes = new HashSet<productInfo>();
        }
    
        public string id { get; set; }
        public string descriptID { get; set; }
        public string projectName { get; set; }
        public string customername { get; set; }
        public int currentStatuID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> createPerson { get; set; }
        public Nullable<double> targetPrice { get; set; }
        public Nullable<decimal> annualDemand { get; set; }
        public string lifeCycle { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<int> productType { get; set; }
        public Nullable<System.DateTime> demoFinishTime { get; set; }
        public Nullable<System.DateTime> testFinishTime { get; set; }
        public Nullable<System.DateTime> smallAmountFinishTime { get; set; }
        public Nullable<System.DateTime> batchFinishTime { get; set; }
        public string instanceID { get; set; }
        public string customerLH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkResult> checkResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer { get; set; }
        public virtual projectStatus projectStatus { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcePath> resourcePath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notice> notices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectStatuChangeInfo> projectStatuChangeInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productInfo> productInfoes { get; set; }
    }
}
