//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectInfo
    {
        public string id { get; set; }
        public string descriptID { get; set; }
        public string projectName { get; set; }
        public string customername { get; set; }
        public string customerLH { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string username { get; set; }
        public string instanceID { get; set; }
    }
}
